Update angular_build_2.yml

diff --git a/.github/workflows/angular_build_2.yml b/.github/workflows/angular_build_2.yml
--- a/.github/workflows/angular_build_2.yml
+++ b/.github/workflows/angular_build_2.yml
@@ -69,7 +69,7 @@ jobs:
 
          # Verify Dockerfile existence for frontend
       - name: Verify Frontend Dockerfile
-        run: test -f ./app-frontend/Dockerfile || (echo "Dockerfile not found in app-frontend" && exit 1)
+        run: test -f ./app-frontend || (echo "Dockerfile not found in app-frontend" && exit 1)
       
    # Build Docker images
       - name: Build Frontend Docker Image
@@ -77,7 +77,7 @@ jobs:
 
   # Verify Dockerfile existence for backend
       - name: Verify Backend Dockerfile
-        run: test -f ./app-backend/Dockerfile || (echo "Dockerfile not found in app-backend" && exit 1)
+        run: test -f ./app-backend || (echo "Dockerfile not found in app-backend" && exit 1)
         
       - name: Build Backend Docker Image
         run: docker build -t mean-stack-backend ./app-backend
